steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'REGION-docker.pkg.dev/PROJECT/dineof-process/dineof-runner', '.' ]
images: ['REGION-docker.pkg.dev/PROJECT/dineof-process/dineof-runner']